<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRp3tssv\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRp3tssv/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRp3tssv.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerRp3tssv\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerRp3tssv\EccubeProdProjectContainer([
    'container.build_hash' => 'Rp3tssv',
    'container.build_id' => 'f072b5b6',
    'container.build_time' => 1623373831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRp3tssv');
