<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6ghfnfh\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6ghfnfh/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6ghfnfh.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6ghfnfh\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \Container6ghfnfh\EccubeDevDebugProjectContainer([
    'container.build_hash' => '6ghfnfh',
    'container.build_id' => 'c113d704',
    'container.build_time' => 1625706487,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6ghfnfh');
