<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbm1sxh\EccubeDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbm1sxh/EccubeDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEbm1sxh.legacy');

    return;
}

if (!\class_exists(EccubeDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEbm1sxh\EccubeDevDebugProjectContainer::class, EccubeDevDebugProjectContainer::class, false);
}

return new \ContainerEbm1sxh\EccubeDevDebugProjectContainer([
    'container.build_hash' => 'Ebm1sxh',
    'container.build_id' => '2ce1a91a',
    'container.build_time' => 1625707568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbm1sxh');
